TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
DB += caen_V965_8.template
DB += caen_V965Debug_8.template


#----------------------------------------------------

include $(TOP)/configure/RULES
include $(TOP)/configure/RULES.Db
#----------------------------------------
#  ADD RULES AFTER THIS LINE

